### ISSUE TITLE
🐞존재하지 않는 계정으로 로그인 시 안내 문구 띄우기

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#27]
## Description

![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/e31c1ebb-56f1-43d3-9f96-30b73f178b38)
회원가입 되어있지 않은 계정으로 로그인 시도 시 어떠한 안내 문구가 보이지 않는다.

## Todo
- [x] 존재하지 않는 계정으로 로그인 시 안내 문구 띄우기
- [x] 회원가입 페이지도 문제가 있는지 확인하기

**Comment by robinyoon-dev** [comment]
# 없는 계정으로 로그인 시...
```
error - pages\api\check-login.js (27:18) @ email
error - TypeError: Cannot read properties of null (reading 'email')
    at handler (webpack-internal:///(api)/./pages/api/check-login.js:26:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\api-utils\node.js:363:9)
    at async DevServer.runApi (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\next-server.js:488:9)
    at async Object.fn (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\next-server.js:750:37)
    at async Router.execute (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\dev\next-dev-server.js:741:20)
    at async DevServer.handleRequest (C:\Users\labin\Desktop\githubs\project\bingo-app\node_modules\next\dist\server\base-server.js:322:20) {
  page: '/api/check-login'
}
  25 |     result,
  26 |     userData: {
> 27 |       email: user.email,
     |                  ^
  28 |       nickname: user.nickname, 
  29 |     }
  30 |   });
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 270 ms (347 modules)
```

**Comment by robinyoon-dev** [comment]
# 현재 api/check-login
```javascript
import { MongoClient } from "mongodb";

async function handler(req, res) {
  const userID = req.query.id;
  const userPW = req.query.pw;
  let result = false;
  const client = await MongoClient.connect(
    "mongodb+srv://robin:robin@cluster0.wymu7lr.mongodb.net/boards?retryWrites=true&w=majority"
  );
  const db = client.db();

  const usersCollection = db.collection("users");

  const user = await usersCollection.findOne({
    email: userID,
    password: userPW,
  });

  if (user !== null) {
    result = true;
  }
  client.close();

  res.status(201).json({
    result,
    userData: {
      email: user.email,
      nickname: user.nickname, 
    }
  });
}

export default handler;
```

**Comment by robinyoon-dev** [comment]
# 해결
api/check-login.js
```javascript
import { MongoClient } from "mongodb";

async function handler(req, res) {
  const userID = req.query.id;
  const userPW = req.query.pw;
  let result = false;
  const client = await MongoClient.connect(
    "mongodb+srv://robin:robin@cluster0.wymu7lr.mongodb.net/boards?retryWrites=true&w=majority"
  );
  const db = client.db();

  const usersCollection = db.collection("users");

  const user = await usersCollection.findOne({
    email: userID,
    password: userPW,
  });

  if (user !== null) {
    result = true;
  }
  client.close();

  if (result === true) {
    res.status(201).json({
      result,
      userData: {
        email: user.email,
        nickname: user.nickname,
      },
    });
  } else {
    res.status(201).json({
      result,
    });
  }
}

export default handler;

```
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/8f2e867f-35e8-474c-a25b-672e8f7d9b8f)
